using UCanAccess.File;
using Xunit;
using Xunit.Abstractions;

namespace UCanAccess.File.Tests;

/// <summary>
/// Cross-check: a file mutated by the port must be readable by the ORIGINAL
/// Jackcess. Requires a JDK on PATH and the oracle jars (regenerated by
/// tools/JavaOracle/run.ps1); skipped when the toolchain is unavailable.
/// </summary>
public class JavaReadsWrittenFileTests
{
    private readonly ITestOutputHelper _output;

    public JavaReadsWrittenFileTests(ITestOutputHelper output) => _output = output;

    private static bool JavaAvailable()
    {
        try
        {
            var psi = new System.Diagnostics.ProcessStartInfo("java", "-version")
            {
                RedirectStandardError = true,
                RedirectStandardOutput = true,
                UseShellExecute = false,
            };
            using var p = System.Diagnostics.Process.Start(psi)!;
            p.WaitForExit(15000);
            return p.ExitCode == 0;
        }
        catch (Exception)
        {
            return false;
        }
    }

    private static string FindRepoRoot()
    {
        string? env = Environment.GetEnvironmentVariable("UCANACCESS_CSHARP_REPO");
        if (!string.IsNullOrEmpty(env) && Directory.Exists(env))
        {
            return env;
        }
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir != null)
        {
            if (Directory.Exists(Path.Combine(dir.FullName, "tools", "JavaOracle")))
            {
                return dir.FullName;
            }
            dir = dir.Parent;
        }
        return AppContext.BaseDirectory;
    }

    private static string? FindJar(string name)
    {
        string? repo = Environment.GetEnvironmentVariable("JUSTYBASE_PARSER_PATH");
        string[] candidates =
        {
            Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "..", "Local", "Temp", "ucanaccess-csharp-oracle", name),
            Path.Combine(Path.GetTempPath(), "ucanaccess-csharp-oracle", name),
        };
        foreach (string c in candidates)
        {
            if (System.IO.File.Exists(c))
            {
                return c;
            }
        }
        return null;
    }

    [Fact]
    public void Jackcess_reads_long_values_written_by_the_port()
    {
        if (!JavaAvailable())
        {
            _output.WriteLine("SKIPPED: java not available");
            throw Xunit.Sdk.SkipException.ForSkip("java not available");
        }
        string? jackJar = FindJar("jackcess-5.1.5.jar");
        if (jackJar == null)
        {
            _output.WriteLine("SKIPPED: jackcess jar not found (run tools/JavaOracle/run.ps1)");
            throw Xunit.Sdk.SkipException.ForSkip("jackcess jar not found (run tools/JavaOracle/run.ps1)");
        }
        string classesDir = Path.Combine(FindRepoRoot(), "tools", "JavaOracle", "classes");
        if (!Directory.Exists(classesDir))
        {
            _output.WriteLine("SKIPPED: oracle classes not compiled (run tools/JavaOracle/run.ps1)");
            throw Xunit.Sdk.SkipException.ForSkip("oracle classes not compiled (run tools/JavaOracle/run.ps1)");
        }

        string src = Path.Combine(AppContext.BaseDirectory, "fixtures", "generated", "genAllTypes.mdb");
        string tmp = Path.Combine(Path.GetTempPath(), $"ucanaccess_java_lval_{Guid.NewGuid():N}.mdb");
        System.IO.File.Copy(src, tmp, true);
        try
        {
            string longMemo = new string('M', 200); // exceeds the 64-byte inline limit
            using (var db = Database.Open(tmp, readOnly: false))
            {
                var t = db.GetTable("t_alltypes")!;
                t.AddRow(new object?[]
                {
                    null, "long value row", longMemo, (short)1, 1, 1.0, 1.0f, 1.0m, 1.0m,
                    new DateTime(2024, 1, 1, 0, 0, 0), false, null,
                    new byte[] { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80 },
                });
            }

            string json = RunDbDump(jackJar, classesDir, tmp);
            _output.WriteLine(json);
            Assert.Contains("long value row", json);
            Assert.Contains(longMemo, json);
        }
        finally
        {
            System.IO.File.Delete(tmp);
        }
    }

    [Fact]
    public void Jackcess_reads_updates_and_deletes_written_by_the_port()
    {
        if (!JavaAvailable())
        {
            _output.WriteLine("SKIPPED: java not available");
            throw Xunit.Sdk.SkipException.ForSkip("java not available");
        }
        string? jackJar = FindJar("jackcess-5.1.5.jar");
        if (jackJar == null)
        {
            _output.WriteLine("SKIPPED: jackcess jar not found (run tools/JavaOracle/run.ps1)");
            throw Xunit.Sdk.SkipException.ForSkip("jackcess jar not found (run tools/JavaOracle/run.ps1)");
        }
        string classesDir = Path.Combine(FindRepoRoot(), "tools", "JavaOracle", "classes");
        if (!Directory.Exists(classesDir))
        {
            _output.WriteLine("SKIPPED: oracle classes not compiled (run tools/JavaOracle/run.ps1)");
            throw Xunit.Sdk.SkipException.ForSkip("oracle classes not compiled (run tools/JavaOracle/run.ps1)");
        }

        string src = Path.Combine(AppContext.BaseDirectory, "fixtures", "generated", "genEmpty.mdb");
        string tmp = Path.Combine(Path.GetTempPath(), $"ucanaccess_java_upd_{Guid.NewGuid():N}.mdb");
        System.IO.File.Copy(src, tmp, true);
        try
        {
            using (var db = Database.Open(tmp, readOnly: false))
            {
                var t = db.GetTable("t_empty")!;
                t.AddRow(new object?[] { null, "row one" });
                t.AddRow(new object?[] { null, "row two" });
                t.AddRow(new object?[] { null, "row three" });
            }

            using (var db = Database.Open(tmp, readOnly: false))
            {
                var t = db.GetTable("t_empty")!;
                var (page, rowNum) = FindRowId(t, "row two");
                t.UpdateRow(page, rowNum, new object?[] { null, "two updated with relocation of a long text" });
                (page, rowNum) = FindRowId(t, "row one");
                t.DeleteRow(page, rowNum);
            }

            string json = RunDbDump(jackJar, classesDir, tmp);
            _output.WriteLine(json);
            Assert.DoesNotContain("row one", json);
            Assert.Contains("two updated with relocation of a long text", json);
            Assert.Contains("row three", json);
        }
        finally
        {
            System.IO.File.Delete(tmp);
        }
    }

    private static (int Page, int RowNumber) FindRowId(File.Table table, string name)
    {
        var pageCursor = table.OwnedPages.Cursor();
        while (true)
        {
            int page = pageCursor.GetNextPage();
            if (page < 0)
            {
                break;
            }
            byte[] buffer = new byte[table.Database.Format.PageSize];
            table.Database.PageChannel.ReadPage(buffer, page);
            int rowsOnPage = File.Table.GetRowsOnDataPage(buffer, table.Database.Format);
            for (int r = 0; r < rowsOnPage; r++)
            {
                File.Row? row = table.GetRow(page, r);
                if (row != null && Equals(row["name"], name))
                {
                    return (page, r);
                }
            }
        }
        throw new InvalidOperationException($"row '{name}' not found");
    }

    private static string RunDbDump(string jackJar, string classesDir, string mdbPath)
    {
        string outJson = Path.Combine(Path.GetTempPath(), $"ucanaccess_java_read_{Guid.NewGuid():N}.json");
        var psi = new System.Diagnostics.ProcessStartInfo("java")
        {
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            UseShellExecute = false,
            WorkingDirectory = classesDir,
        };
        psi.ArgumentList.Add("-Duser.timezone=UTC");
        psi.ArgumentList.Add("-cp");
        psi.ArgumentList.Add($"{jackJar}{Path.PathSeparator}{classesDir}");
        psi.ArgumentList.Add("DbDump");
        psi.ArgumentList.Add(mdbPath);
        psi.ArgumentList.Add(outJson);
        using var p = System.Diagnostics.Process.Start(psi)!;
        string err = p.StandardError.ReadToEnd();
        p.WaitForExit(60000);
        Assert.True(p.ExitCode == 0, $"DbDump failed: {err}");
        string json = System.IO.File.ReadAllText(outJson);
        System.IO.File.Delete(outJson);
        return json;
    }

    [Fact]
    public void Jackcess_reads_rows_written_by_the_port()
    {
        if (!JavaAvailable())
        {
            _output.WriteLine("SKIPPED: java not available");
            throw Xunit.Sdk.SkipException.ForSkip("java not available");
        }
        string? jackJar = FindJar("jackcess-5.1.5.jar");
        if (jackJar == null)
        {
            _output.WriteLine("SKIPPED: jackcess jar not found (run tools/JavaOracle/run.ps1)");
            throw Xunit.Sdk.SkipException.ForSkip("jackcess jar not found (run tools/JavaOracle/run.ps1)");
        }
        string repo = FindRepoRoot();
        string classesDir = Path.Combine(repo, "tools", "JavaOracle", "classes");
        if (!Directory.Exists(classesDir))
        {
            _output.WriteLine("SKIPPED: oracle classes not compiled (run tools/JavaOracle/run.ps1)");
            throw Xunit.Sdk.SkipException.ForSkip("oracle classes not compiled (run tools/JavaOracle/run.ps1)");
        }

        // 1. port writes rows into a copy of genEmpty
        string src = Path.Combine(AppContext.BaseDirectory, "fixtures", "generated", "genEmpty.mdb");
        string tmp = Path.Combine(Path.GetTempPath(), $"ucanaccess_java_read_{Guid.NewGuid():N}.mdb");
        System.IO.File.Copy(src, tmp, true);
        try
        {
            using (var db = Database.Open(tmp, readOnly: false))
            {
                var t = db.GetTable("t_empty")!;
                t.AddRow(new object?[] { null, "written by port" });
                t.AddRow(new object?[] { null, "second row" });
            }

            // 2. the original Jackcess reads it back
            string json = RunDbDump(jackJar, classesDir, tmp);
            _output.WriteLine(json);
            Assert.Contains("t_empty", json);
            Assert.Contains("written by port", json);
            Assert.Contains("second row", json);
            // auto-numbered ids must be present
            Assert.Contains("1,\"written by port\"", json);
            Assert.Contains("2,\"second row\"", json);
        }
        finally
        {
            System.IO.File.Delete(tmp);
        }
    }
}
